In [2]:
import torch

torch.arange(12).reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [4]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [5]:
torch.ones((2,4,5))

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [12]:
# broadcast mechanism
print(torch.arange(2).reshape(2,1))
print('\n')
print(torch.arange(3).reshape(1,3))
print('\n')
print(torch.arange(2).reshape(2,1) + torch.arange(3).reshape(1,3))

tensor([[0],
        [1]])


tensor([[0, 1, 2]])


tensor([[0, 1, 2],
        [1, 2, 3]])


In [8]:
torch.arange(2).reshape(2,1)

tensor([[0],
        [1]])