1. 依照课件3中的内容给出测算三角波（triangle_wave（））y1、y2、y3、y4四种方式的计算速度与结果比较的代码，并对其运算显示结果。

In [1]:
import numpy as np
import time

# define triangle_wave function
def triangle_wave(x, c_tri, c_peak, h_peak):
    x = x - int(x) # get fractional part becauce the cycle of triangle wave is 1
    if x >= c_tri:
        y = 0.0 # y means the value of y axis
    elif x < c_peak:
        y = x * h_peak / c_peak
    else:
        y = (x-c_tri) * (h_peak / (c_peak-c_tri))
    return y

x = np.linspace(0, 2, 1000)
# time point 1
start_1 = time.perf_counter()
y_1 = np.array([triangle_wave(i, 0.6, 0.4, 1.0) for i in x])
# time point 2
end_1 = time.perf_counter()
print(f"y1 expands {end_1-start_1} seconds")


triangle_ufunc_1 = np.frompyfunc(triangle_wave, 4, 1)
# time point 3
start_2 = time.perf_counter()
y_2 = triangle_ufunc_1(x, 0.6, 0.4, 1.0)
# time point 4
end_2 = time.perf_counter()
print(f"y2 expands {end_2-start_2} seconds")


triangle_ufunc_2 = np.frompyfunc(lambda x: triangle_wave(x, 0.6, 0.4, 1), 1, 1)
# time point 5
start_3 = time.perf_counter()
y_3 = triangle_ufunc_2(x)
# time point 6
end_3 = time.perf_counter()
print(f"y3 expands {end_3-start_3} seconds")


triangle_ufunc_3 = np.vectorize(triangle_wave, otypes=[np.float64])
# time point 7
start_4 = time.perf_counter()
y_4 = triangle_ufunc_3(x, 0.6, 0.4, 1.0)
end_4 = time.perf_counter()
print(f"y4 expands {end_4-start_4} seconds")

print(np.all(y_1 == y_2))
print(np.all(y_2 == y_3))
print(np.all(y_3 == y_4))

y1 expands 0.000560723999910806 seconds
y2 expands 0.00025856999991447083 seconds
y3 expands 0.0002707099999952334 seconds
y4 expands 0.0002821080000785514 seconds
True
True
True


2. arr11 = 5-np.arange(1,13).reshape(4,3), 计算所有元素及每一列的和；  
对每一个元素、每一列求累积和；  
计算每一行的累计积；  
计算所有元素的最小值；  
计算每一列的最大值；  
计算所有元素、每一行的均值；  
计算所有元素、每一列的中位数；  
计算所有元素的方差，每一行的标准差。  

In [2]:
import numpy as np

# create data
arr_1 = 5 - np.arange(1, 13).reshape(4, 3)

# calculate sum of each column
print(f"the sum of each column is {np.sum(arr_1, axis=0)}")
# calculate the cumulative sum of each element
print(f"the cumulative sum of each element is {np.cumsum(arr_1)}")
# calculate the cumulative sum of each column
print(f"the cumulative sum of each column is: \n {np.cumsum(arr_1, axis=0)}")
# calculate the cumulative product of each row
print(f"the cumulative product of each row is: \n{np.cumprod(arr_1, axis=1)}")
# calculate min of all elements
print(f"the min value of all elements is {np.min(arr_1)}")
# calculate the max of each column
print(f"the max value of each column is {np.max(arr_1, axis=0)}")
# calculate the average of all elements
print(f"the mean value of all elements is {np.mean(arr_1)}")
# calculate the average of each row
print(f"the mean value of each row is {np.mean(arr_1, axis=1)}")
# calculate the median of all elements
print(f"the median of all elements is {np.median(arr_1)}")
# calcualte the median of each column
print(f"the median of each column is {np.median(arr_1, axis=0)}")
# calculate the variance of all elements
print(f"the variance of all elements is {np.var(arr_1)}")
# calculate the standard deviation of each row
print(f"the standard deviation of each row is {np.std(arr_1, axis=1)}")

the sum of each column is [ -2  -6 -10]
the cumulative sum of each element is [  4   7   9  10  10   9   7   4   0  -5 -11 -18]
the cumulative sum of each column is: 
 [[  4   3   2]
 [  5   3   1]
 [  3   0  -3]
 [ -2  -6 -10]]
the cumulative product of each row is: 
[[   4   12   24]
 [   1    0    0]
 [  -2    6  -24]
 [  -5   30 -210]]
the min value of all elements is -7
the max value of each column is [4 3 2]
the mean value of all elements is -1.5
the mean value of each row is [ 3.  0. -3. -6.]
the median of all elements is -1.5
the median of each column is [-0.5 -1.5 -2.5]
the variance of all elements is 11.916666666666666
the standard deviation of each row is [0.81649658 0.81649658 0.81649658 0.81649658]


3. 在数组[1, 2, 3, 4, 5]中每相邻两个数字中间插入两个0

In [3]:
# create data
arr_2 = np.array([1, 2, 3, 4, 5])

# insert two zero between adjacent number
for i in range(len(arr_2)):
    arr_2 = np.insert(arr_2, np.where(arr_2 == i+1)[0][0], [0, 0])

print(arr_2)


[0 0 1 0 0 2 0 0 3 0 0 4 0 0 5]


4. 归一化，将矩阵规格化到0～1，即最小的变成0，最大的变成1，最小与最大之间的等比缩放。试对Z = np.random.random((5,5))进行归一化。

In [4]:
# set seed and create data
np.random.seed(1026)
z = np.random.random((5, 5))

def normalization(x):
    min_x = np.min(x)
    max_x = np.max(x)
    result = (x-min_x) / (max_x-min_x)

    return result

print(normalization(z))

[[0.33911304 0.87412518 1.         0.15854379 0.38122249]
 [0.2668365  0.70647226 0.04477112 0.         0.87791292]
 [0.11355699 0.54382964 0.35584635 0.66999999 0.94904989]
 [0.78396858 0.63934665 0.66972279 0.12357888 0.27952779]
 [0.73018948 0.27691111 0.67533854 0.37772504 0.89328116]]


5. 找出数组中与给定值最接近的数（通用方法）。（例：任一数组Z=array([[0,1,2,3],[4,5,6,7]])，给任一定值z=5.1，如何找出Z中的5）

In [5]:
# creata data
arr_3 = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7]])

z = 5.1

print(f"the nearest number of z is {arr_3[np.where(np.abs(z-arr_3) == np.min(np.abs(z-arr_3)))][0]}")

the nearest number of z is 5


6. 解方程：3x + 6y -5z = 12；x-3y+2z = -2；5x -y +4z = 10。

In [6]:
unknown_variable = np.array([[3, 1, 5], [6, -3, -1], [-5, 2, 4]])
c = np.array([12, -2, 10])

print(f"the x, y, z is {np.linalg.solve(unknown_variable, c)} respectively")

the x, y, z is [-0.125  -0.4375  2.5625] respectively


7. 参见课件4第46页，对g(y)在100个切比雪夫节点之上分別使用Polynomial（Polynomial.fit）和Chebyshev（Chebyshev.fit）进行插值，在[-1,1]区间上取1000个等距点对误差进行比较。g(x)= sin(z**2) + sin(z)**2, 其中z=(x - 1) * 5。

In [75]:
from numpy.polynomial import Polynomial, Chebyshev

# define the function
def z(x):
    return 5*(x-1)

def g(x):
    return np.sin(x**2) + (np.sin(x)**2)

# create data
n = 100
xd = np.linspace(-1, 1, 1000)
x_fit = Chebyshev.basis(n).roots()

function_1 = Polynomial.fit(x_fit, g(z(x_fit)), n-1, domain=[-1, 1])
function_2 = Chebyshev.fit(x_fit, g(z(x_fit)), n-1, domain=[-1, 1])

print(abs(function_1(xd) - g(z(xd))).max())
print(abs(function_2(xd) - g(z(xd))).max())

1.195298137963622
6.475744385170401e-09


/home/ouyangkang/software/anaconda3/envs/ML/lib/python3.9/site-packages/numpy/polynomial/polynomial.py:1361: RankWarning: The fit may be poorly conditioned
  return pu._fit(polyvander, x, y, deg, rcond, full, w)


8. 试用bincount()函数替代histogram()函数完成统计男青少年年龄和身高的例子的计算（数据见height.csv）

In [77]:
height_data = np.loadtxt('/mnt/c/Users/ouyangkang/Downloads/height.csv', delimiter=',')

height_data = np.round(height_data).astype('int')

ages = height_data[:, 0]
heights = height_data[:, 1]

rounded_heights = np.round(heights).astype(int)
age_counts = np.bincount(ages)
age_total_heights = np.bincount(ages, weights=rounded_heights)
average_heights = age_total_heights / age_counts

for age, average_height in enumerate(average_heights):
    if age_counts[age] > 0:
        print(f"年龄 {age} 的平均身高为 {average_height:.2f} 厘米")

年龄 7 的平均身高为 125.14 厘米
年龄 8 的平均身高为 129.86 厘米
年龄 9 的平均身高为 134.83 厘米
年龄 10 的平均身高为 142.12 厘米
年龄 11 的平均身高为 145.50 厘米
年龄 12 的平均身高为 152.00 厘米
年龄 13 的平均身高为 158.86 厘米
年龄 14 的平均身高为 164.50 厘米
年龄 15 的平均身高为 169.60 厘米
年龄 16 的平均身高为 173.78 厘米
年龄 17 的平均身高为 174.17 厘米
年龄 18 的平均身高为 174.12 厘米
年龄 19 的平均身高为 175.08 厘米
年龄 20 的平均身高为 175.00 厘米


/tmp/ipykernel_334/2655687582.py:11: RuntimeWarning: invalid value encountered in true_divide
  average_heights = age_total_heights / age_counts


9. 使用二项分布进行赌博计算.  同时抛5枚硬币，如果正面朝上少于3枚，则输掉8元，否则就赢8元。如果手中有1000元作为赌资，请问赌博10000次后可能会是什么情况呢？(参见课件)

In [79]:
current_money = np.zeros(10000)
current_money[0] = 1000

np.random.seed(648)
game_condition = np.random.binomial(5, 0.5, 10000)

for i in range(len(game_condition)):
    if game_condition[i] < 3:
        if i == 0:
            current_money[i] = current_money[i] - 8
        else:
            if current_money[i-1] > 0:
                current_money[i] = current_money[i-1] - 8
            else:
                raise AssertionError(f"Without enough money {current_money[i+1]}")
    elif game_condition[i] >= 3:
        if i == 0:
            current_money[i] = current_money[i] + 8
        else:
            if current_money[i-1] > 0:
                current_money[i] = current_money[i-1] + 8
            else:
                raise AssertionError(f"Without enough money {current_money[i+1]}")
    
print(current_money.reshape(100, 100))

[[ 992.  984.  992. ...  952.  960.  968.]
 [ 960.  952.  944. ... 1048. 1056. 1048.]
 [1056. 1048. 1040. ... 1064. 1072. 1064.]
 ...
 [1280. 1272. 1280. ... 1256. 1264. 1256.]
 [1248. 1240. 1248. ... 1240. 1248. 1240.]
 [1232. 1240. 1248. ... 1176. 1168. 1160.]]
