In [1]:
import torch
print(torch.__version__)

1.13.1


In [2]:
# tensor
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
# shape
x.shape

torch.Size([12])

In [4]:
# total count
x.numel()

12

In [5]:
# reshape
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
# zero matrix
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
# one matrix
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
# random tensor
torch.randn(3,4)

tensor([[ 0.5758, -1.1341,  0.2927,  1.5295],
        [-1.3681,  1.3986,  0.5632,  0.5647],
        [-2.2748,  1.6042,  0.0995, -1.9736]])